no_work<>何もしない<>7
res_del<>レス削除<>1
res_reb<>レス復活<>1
res_edit<>レス編集<>4
info_open<>端末情報公開<>4
info_close<>端末情報非公開<>4
img_del<>投稿画像削除<>4
res_clr<>レス透明削除<>4
index<>索引再構築<>7
thread_stop<>スレッド停止<>2
thread_rest<>スレッド再開<>2
thread_rename<>スレタイ変更<>2
thread_move<>ボード間移動<>2
thread_clr<>スレッド消去<>2
dat_upload<>datアップロード<>2
move_kako<>過去ログ倉庫移動<>2
admin_write<>管理者投稿<>7
admin_thread<>管理者スレ立て<>4
index_rw<>index.html更新<>4
rule_ed<>ローカルルール編集<>4
setting_edit<>ボード設定変更<>4
banner_ed<>バナー編集<>16
last_txt<>終了レス編集<>2
nonames<>携帯版名無し編集<>4
ng_set_board<>規制設定<>4
member_board<>管理者設定<>7
view_board<>ボードを見る<>7
board_make<>ボード作成<>16
board_del<>ボード削除<>16
header_edit<>Headタグ編集<>4
line<>-----境界線横-----<>7
init<>初期設定<>16
category<>カテゴリ設定<>16
maintenance<>メンテナンス告知<>16
rebuild<>掲示板再構築<>16
pic_up<>画像アップロード<>4
pic_del<>画像ファイル削除<>4
browser<>専ブラ設定<>16
top_page<>トップページ編集<>16
ng_setting<>規制設定<>4
member<>管理者設定<>4
